{
  "formatVersion": "1.1",
  "component": {
    "url": "../../paging-common/3.3.0/paging-common-3.3.0.module",
    "group": "androidx.paging",
    "module": "paging-common",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-release.aar",
          "url": "paging-common-android-3.3.0.aar",
          "size": 678277,
          "sha512": "f169b6742e58050eb46a16e2c3bf6a217f80d1996d1b3e0723e4fce889acd5c5b289eeb175c70ce3eeab45758097a142ead81a8e6b829ab49a9c70a9b7d706d9",
          "sha256": "7c536689141a77b2c1611b549380acbe1a7b8a9571f3335a215f29ccf5e9b8ef",
          "sha1": "3d1d10ce5fcfdd47e4d822d83e13fadf7af56ba1",
          "md5": "0008c1221507378d1eb188869be6822b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-release.aar",
          "url": "paging-common-android-3.3.0.aar",
          "size": 678277,
          "sha512": "f169b6742e58050eb46a16e2c3bf6a217f80d1996d1b3e0723e4fce889acd5c5b289eeb175c70ce3eeab45758097a142ead81a8e6b829ab49a9c70a9b7d706d9",
          "sha256": "7c536689141a77b2c1611b549380acbe1a7b8a9571f3335a215f29ccf5e9b8ef",
          "sha1": "3d1d10ce5fcfdd47e4d822d83e13fadf7af56ba1",
          "md5": "0008c1221507378d1eb188869be6822b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-android-3.3.0-sources.jar",
          "url": "paging-common-android-3.3.0-sources.jar",
          "size": 157059,
          "sha512": "c50d3c11d4044e8c655f51f9a474430ee14f1385890845d70e660ebaa38fe6bbf7fdcc3d4bff140bec42094a1f0614c259dd033012feebabc07beb53d66d1799",
          "sha256": "5ed5cb62f80f44b7dd82644590040bfed6cc413ccfcccd843c298386f0d87aa7",
          "sha1": "48e626e1880490a6882d4ea311cfb28469027b84",
          "md5": "b0dbede9b5410bd80bce5f31a0bf80f1"
        },
        {
          "name": "paging-common-3.3.0-samples-sources.jar",
          "url": "paging-common-android-3.3.0-samples-sources.jar",
          "size": 40591,
          "sha512": "cbdd887c89003f6b02e6d351773c1559a0dbef7b10cbe911b23cca6356a342b14e594999a9760eee35148e941d87f9005d86db0f299f9a5c4c5201f2e6219625",
          "sha256": "e38a380af1a161410207cb358cb5fcf1ec844432d92a5c9a741524a4767ef970",
          "sha1": "a577b372155d466531746351cd9d1dfb4812d0d5",
          "md5": "6a209d35769c6bb11bbca1bcbcd5b8ad"
        }
      ]
    }
  ]
}