{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-common",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-3.3.0-multiplatform-sources.jar",
          "url": "paging-common-3.3.0-multiplatform-sources.jar",
          "size": 163592,
          "sha512": "834dd029b7ac7aa7f57c480c97cb7d643d4d716cd0d690fbae74fc2d8e6aed48e049b534fcc00fcaf8d21bdfdc875c89e556305725b0f6e8609e719d53e4ae46",
          "sha256": "28925c8d7687c749726e599e2a66dbe266c6da3260a3470ea249da3f3dfb0c68",
          "sha1": "1d9c460c8d1c06119aef69349b54a1ad9ff3736f",
          "md5": "11de9328650ebde2cbe322f0dad7c937"
        },
        {
          "name": "paging-common-3.3.0-samples-sources.jar",
          "url": "paging-common-3.3.0-samples-sources.jar",
          "size": 40591,
          "sha512": "cbdd887c89003f6b02e6d351773c1559a0dbef7b10cbe911b23cca6356a342b14e594999a9760eee35148e941d87f9005d86db0f299f9a5c4c5201f2e6219625",
          "sha256": "e38a380af1a161410207cb358cb5fcf1ec844432d92a5c9a741524a4767ef970",
          "sha1": "a577b372155d466531746351cd9d1dfb4812d0d5",
          "md5": "6a209d35769c6bb11bbca1bcbcd5b8ad"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "paging-common-3.3.0-versionMetadata.json",
          "size": 35834,
          "sha512": "94c023fd2ba63aac717e49876dd5688a9b314e6d0593926b11f02d8d2f8a24f64df3e6adc38500e213be04e753480bac541ed00eb0ead1259ea973ab414c7598",
          "sha256": "fbd058724e7dfda2502fea9cd82260ec3444f2c002275e4254eb8ef49bd6716c",
          "sha1": "f952d81ce4e5c34e806e8a852036146d4ff4dc03",
          "md5": "9689fa74b3033486a6c4cecabb89aabb"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-metadata-3.3.0.jar",
          "url": "paging-common-3.3.0.jar",
          "size": 24769,
          "sha512": "b02d2d99594033aec1693774235795482220d810a89cb72767fa39b12b1b4cec1ae6f8ba9acff1814a2e5200184e7f018fc2a88d14840eb92cb6e8c53537db27",
          "sha256": "3a00bde031ca057829a9e5c1722322a7660379033498f2a1ec837f33506f7e2b",
          "sha1": "c35c269a6247f5b0604293032714594720079509",
          "md5": "bb0eb5a8bb5e7e476218142b29d9be69"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-kotlin-3.3.0-sources.jar",
          "url": "paging-common-3.3.0-sources.jar",
          "size": 159655,
          "sha512": "897a9eba5e113ede0cb85f220390746c05d819ecfecaf38a1d36441b752aae09e615092671445fee3ab960474eaccaec9e514aaa6d3d2771059ba1eab3464b8e",
          "sha256": "e1822c5db179bb143e5a98c4b9d6a633873c9b9db7d788f7657731f84cff6f96",
          "sha1": "21a97cb9a48ea4a25088166da1083981a655ae31",
          "md5": "0d5d6acf95071667451eb34449879f2c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-common-android/3.3.0/paging-common-android-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-android",
        "version": "3.3.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-common-android/3.3.0/paging-common-android-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-android",
        "version": "3.3.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-common-android/3.3.0/paging-common-android-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-android",
        "version": "3.3.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-iosarm64/3.3.0/paging-common-iosarm64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-iosarm64",
        "version": "3.3.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-iosarm64/3.3.0/paging-common-iosarm64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-iosarm64",
        "version": "3.3.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-iosarm64/3.3.0/paging-common-iosarm64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-iosarm64",
        "version": "3.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-iossimulatorarm64/3.3.0/paging-common-iossimulatorarm64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-iossimulatorarm64",
        "version": "3.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-iossimulatorarm64/3.3.0/paging-common-iossimulatorarm64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-iossimulatorarm64",
        "version": "3.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-iossimulatorarm64/3.3.0/paging-common-iossimulatorarm64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-iossimulatorarm64",
        "version": "3.3.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-iosx64/3.3.0/paging-common-iosx64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-iosx64",
        "version": "3.3.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-iosx64/3.3.0/paging-common-iosx64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-iosx64",
        "version": "3.3.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-iosx64/3.3.0/paging-common-iosx64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-iosx64",
        "version": "3.3.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../paging-common-jvm/3.3.0/paging-common-jvm-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-jvm",
        "version": "3.3.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../paging-common-jvm/3.3.0/paging-common-jvm-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-jvm",
        "version": "3.3.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../paging-common-jvm/3.3.0/paging-common-jvm-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-jvm",
        "version": "3.3.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-linuxx64/3.3.0/paging-common-linuxx64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-linuxx64",
        "version": "3.3.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-linuxx64/3.3.0/paging-common-linuxx64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-linuxx64",
        "version": "3.3.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-macosarm64/3.3.0/paging-common-macosarm64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-macosarm64",
        "version": "3.3.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-macosarm64/3.3.0/paging-common-macosarm64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-macosarm64",
        "version": "3.3.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-macosarm64/3.3.0/paging-common-macosarm64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-macosarm64",
        "version": "3.3.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-macosx64/3.3.0/paging-common-macosx64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-macosx64",
        "version": "3.3.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-macosx64/3.3.0/paging-common-macosx64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-macosx64",
        "version": "3.3.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-macosx64/3.3.0/paging-common-macosx64-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-common-macosx64",
        "version": "3.3.0"
      }
    }
  ]
}