{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-runtime",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.3.0.aar",
          "url": "paging-runtime-3.3.0.aar",
          "size": 90682,
          "sha512": "de8308e65480cd7146c471ed356d3f08087a7ce8ca442af4a1c8ac7e3045b5c6a2c587dc599f1ad6918a4c20d99e9b103645a181c82abec34c758422a3ac0681",
          "sha256": "1f7d21f225e7a549224f54f23900d90e9b7e0594bf503a45b531b70f5f2dd257",
          "sha1": "bd752b40b6cff905c28a928c458baf4771486b6f",
          "md5": "2c3528da6e7f3d7ecd201528cc0f1cab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.3.0.aar",
          "url": "paging-runtime-3.3.0.aar",
          "size": 90682,
          "sha512": "de8308e65480cd7146c471ed356d3f08087a7ce8ca442af4a1c8ac7e3045b5c6a2c587dc599f1ad6918a4c20d99e9b103645a181c82abec34c758422a3ac0681",
          "sha256": "1f7d21f225e7a549224f54f23900d90e9b7e0594bf503a45b531b70f5f2dd257",
          "sha1": "bd752b40b6cff905c28a928c458baf4771486b6f",
          "md5": "2c3528da6e7f3d7ecd201528cc0f1cab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.3.0-sources.jar",
          "url": "paging-runtime-3.3.0-sources.jar",
          "size": 38957,
          "sha512": "da2dc40bac773cb02ae993ad4fb50d7e4e735c6f46e7ea1ef2bda6b1f5ab933ebbe214cb3812ebd3130344e53f4a4ee3df4135c61114dfab15a0f8d642ca2fee",
          "sha256": "03cbef45feb2c80096f6bdc9965dff60c309c718733b609a80c9da2d0d47db20",
          "sha1": "a0a5e57f786b2fad0e3b930c780c3374e7a51513",
          "md5": "55f3e7bc18d6d044a4c8c12d894d7037"
        },
        {
          "name": "paging-runtime-3.3.0-samples-sources.jar",
          "url": "paging-runtime-3.3.0-samples-sources.jar",
          "size": 40591,
          "sha512": "cbdd887c89003f6b02e6d351773c1559a0dbef7b10cbe911b23cca6356a342b14e594999a9760eee35148e941d87f9005d86db0f299f9a5c4c5201f2e6219625",
          "sha256": "e38a380af1a161410207cb358cb5fcf1ec844432d92a5c9a741524a4767ef970",
          "sha1": "a577b372155d466531746351cd9d1dfb4812d0d5",
          "md5": "6a209d35769c6bb11bbca1bcbcd5b8ad"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-runtime is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.3.0-versionMetadata.json",
          "url": "paging-runtime-3.3.0-versionMetadata.json",
          "size": 12559,
          "sha512": "8a3bf6066beb56db00b20962a9de49e6e6c8c8880a94966f9596718ef50442b4851a5c41f2f641da9419dcdeb0c0443d6c431dacaeaeacb40520085ebbe64a69",
          "sha256": "f07e69c99925de6fb05e4c9b8268bcd95046e28cb9b2eead07e25b88c4801e15",
          "sha1": "6c26a520cd46454034edc28b5d25c5efb835b48e",
          "md5": "e45cf12b1abfd0e4527304473617604e"
        }
      ]
    }
  ]
}