{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-compose",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-compose-3.3.0-multiplatform-sources.jar",
          "url": "paging-compose-3.3.0-multiplatform-sources.jar",
          "size": 7380,
          "sha512": "7be4d3b8af51f7ba1cd5f70406b8c34a0730d3562d27b7e8f1fee1b87efa935ef60ecc938933893de7fac558d02a085fe3881565d5c0553f774abdfb8d75a5f3",
          "sha256": "25324645a76fc1498fd2b201850798cde215c3a8294bada2c9e7f9d01dea98a7",
          "sha1": "b766c608dd040d7f198ae39b79a2e99537b45355",
          "md5": "5b278d94892c96cc5cecf24d56248236"
        },
        {
          "name": "paging-compose-3.3.0-samples-sources.jar",
          "url": "paging-compose-3.3.0-samples-sources.jar",
          "size": 6202,
          "sha512": "83a760566dc4b88ffc94aa01435a1410ba4146d282209cfdafe12a8a643ea75a320580f5c45ef2f72d45f13f0a004d0daf2b7ae0f2dae1a42d9731fcb282a6bc",
          "sha256": "27d1b6075e7e872a64be2224a321b763fbf291c46847efa5f26ca60127a98508",
          "sha1": "ca26a0c735c804f50802d6a9bfd5d86acdc4bbdf",
          "md5": "d70812003680936ca1fffde2ddc393c1"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "paging-compose-3.3.0-versionMetadata.json",
          "size": 1009,
          "sha512": "9e8e72961add9e3321de8f6860792095ac0821fdc74fca5841a18d7eef1f651c4be5f09fa7107ff3b840a12af9bcc6be9255c065f139f206c7b396a18a221d89",
          "sha256": "66277980c03ee548b9dbedfa7ca470e04fa2535dd7ee2282754e2d3b95b7dc73",
          "sha1": "f9024b9e717aecf3e7d4b381ae3fe0c407ec4f53",
          "md5": "fa764ce0eb3fb760ae7b8e6c00f9cdbc"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-compose-metadata-3.3.0.jar",
          "url": "paging-compose-3.3.0.jar",
          "size": 708,
          "sha512": "e2957ce6974e11a185e4386cee42df00c9d4699a81960d16b816290c169fae789b4bd4035ff57413c98e1f1347ccf3b8b750a5b7f57c8d75439d0a74dc937930",
          "sha256": "525acf721cc8ac1d49d2365c2041480576be89dca90f1e0305efa14c3b95a52c",
          "sha1": "a73d359ea531a1f983dd5531ecc9ce9ac06e7370",
          "md5": "8435e46101bda42232b89929b6f5fdea"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-compose-kotlin-3.3.0-sources.jar",
          "url": "paging-compose-3.3.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-compose-android/3.3.0/paging-compose-android-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-compose-android",
        "version": "3.3.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-compose-android/3.3.0/paging-compose-android-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-compose-android",
        "version": "3.3.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-compose-android/3.3.0/paging-compose-android-3.3.0.module",
        "group": "androidx.paging",
        "module": "paging-compose-android",
        "version": "3.3.0"
      }
    }
  ]
}