{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-navigation-compose",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-compose-1.0.0.aar",
          "url": "hilt-navigation-compose-1.0.0.aar",
          "size": 4121,
          "sha512": "50e17619830d76bd2cb748836587dc11e1be9f4ef671702db4608251bc952fb6b939e2f030d3eccdc85deb60666d21044dc5449a545d3cdcc165394a58fd6a8e",
          "sha256": "48b79ff9c0dec0b2bb4804ab24d08f9e11e840790f5e69ca38a6590e2c0375e0",
          "sha1": "fdb7c870086027e15f06735476afe9e38418230c",
          "md5": "3e15fb721425b074c7ff68d6764b220b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-compose-1.0.0.aar",
          "url": "hilt-navigation-compose-1.0.0.aar",
          "size": 4121,
          "sha512": "50e17619830d76bd2cb748836587dc11e1be9f4ef671702db4608251bc952fb6b939e2f030d3eccdc85deb60666d21044dc5449a545d3cdcc165394a58fd6a8e",
          "sha256": "48b79ff9c0dec0b2bb4804ab24d08f9e11e840790f5e69ca38a6590e2c0375e0",
          "sha1": "fdb7c870086027e15f06735476afe9e38418230c",
          "md5": "3e15fb721425b074c7ff68d6764b220b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-navigation-compose-1.0.0-sources.jar",
          "url": "hilt-navigation-compose-1.0.0-sources.jar",
          "size": 1914,
          "sha512": "0653eee285376198f4fcddf1fb5ad6c8bf31e23a127ac1af6904510fe96432031438e4724ac6031a55e0cbd4b6c07c683ef23324abf11e19c6f6a05467a6c0b9",
          "sha256": "7075aada6260fde53e239396c412b67704e7d532b4975355e4661c8deb177bd4",
          "sha1": "3a0a679032803da2bd15dc1c0468c31076ac1c71",
          "md5": "d83e4b241ae4f1089255b56bfbd8ba74"
        }
      ]
    }
  ]
}
