{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-navigation",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7309742"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.35"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-1.0.0.aar",
          "url": "hilt-navigation-1.0.0.aar",
          "size": 5264,
          "sha512": "a45b6e41916e2f4dd8464b390cdea288d3f05f7ff4ca862791a02a18b0659ee62c291e776e734d92607b7b8c4549afce3b2883e2cbd7ddb8d8b152c25bdf55a0",
          "sha256": "a1a17a8c8effe001d8fe5f07c6e7149db800047b65f2dc84528eb1cf3fd0e16d",
          "sha1": "5e311ee8d37ff6bed55b458cda8929239dc871ce",
          "md5": "160584b789c9a139b363867a5e1ed610"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.35"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-1.0.0.aar",
          "url": "hilt-navigation-1.0.0.aar",
          "size": 5264,
          "sha512": "a45b6e41916e2f4dd8464b390cdea288d3f05f7ff4ca862791a02a18b0659ee62c291e776e734d92607b7b8c4549afce3b2883e2cbd7ddb8d8b152c25bdf55a0",
          "sha256": "a1a17a8c8effe001d8fe5f07c6e7149db800047b65f2dc84528eb1cf3fd0e16d",
          "sha1": "5e311ee8d37ff6bed55b458cda8929239dc871ce",
          "md5": "160584b789c9a139b363867a5e1ed610"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-navigation-1.0.0-sources.jar",
          "url": "hilt-navigation-1.0.0-sources.jar",
          "size": 1678,
          "sha512": "014ed2449ad70f60d99c38928a62d618cafdd8a6b1dffcabca97a4bf2f4e2fd8589c10a9ffc564619cb0d8df7c831b3e5971df6567375c2546a0188c87e20ce5",
          "sha256": "3bd46db3909eb4b9950cc5dd29a966d476325108824ed617e4871a0bbb92da95",
          "sha1": "45a53a5fe7211c80af2d58743cb5e5f8afcbd0ab",
          "md5": "da4128bcbb4f4719eeba0145423af076"
        }
      ]
    }
  ]
}
